url: https://anandijawkar.github.io
baseurl: https://anandijawkar.github.io

# Site settings
title: Anandi Jawkar
email: anandim30@gmail.com
description: "Hey, I'm Anandi Jawkar, a Computer Science and Business Administration (Double Degree) student @ University of 
Waterloo. Always learning and growing"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/anandijawkar/
  - title: linkedin 
    url: https://www.linkedin.com/in/anandijawkar/
  - title: github
    url: http://github.com/anandijawkar

# Build settings
markdown: kramdown
permalink: pretty
